In [1]:
!pip install jupysql psycopg2-binary

Requirement already satisfied: jupysql in c:\users\medha\anaconda3\lib\site-packages (0.10.16)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: prettytable>=3.12.0 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (3.12.0)
Requirement already satisfied: sqlalchemy in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (2.0.34)
Requirement already satisfied: sqlparse in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (0.5.3)
Requirement already satisfied: ipython-genutils>=0.1.0 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (3.1.4)
Requirement already satisfied: sqlglot>=11.3.7 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (26.0.1)
Requirement already satisfied: jupysql-plugin>=0.4.2 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in c:\users\medha\anaconda3\lib\site-packages (from jupysql) (0.2.26)
Requirement already satisfied: pyyaml in c:\users\medha\anaconda3\lib\site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.1)
Requirement already satisfied: posthog in c:\users\medha\anaconda3\lib\site-packages (from ploomber-core>=0.2.7->jupysql) (3.6.5)
Requirement already satisfied: wcwidth in c:\users\medha\anaconda3\lib\site-packages (from prettytable>=3.12.0->jupysql) (0.2.5)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\medha\anaconda3\lib\site-packages (from jinja2->jupysql) (2.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\medha\anaconda3\lib\site-packages (from sqlalchemy->jupysql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\medha\anaconda3\lib\site-packages (from sqlalchemy->jupysql) (3.0.1)
Requirement already satisfied: requests<3.0,>=2.7 in c:\users\medha\anaconda3\lib\site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.32.3)
Requirement already satisfied: six>=1.5 in c:\users\medha\anaconda3\lib\site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.16.0)
Requirement already satisfied: monotonic>=1.5 in c:\users\medha\anaconda3\lib\site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (1.6)
Requirement already satisfied: backoff>=1.10.0 in c:\users\medha\anaconda3\lib\site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: python-dateutil>2.1 in c:\users\medha\anaconda3\lib\site-packages (from posthog->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\medha\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\medha\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\medha\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\medha\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog->ploomber-core>=0.2.7->jupysql) (2024.12.14)
Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.2 MB ? eta -:--:--
   --------------------------- ------------ 0.8/1.2 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 2.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10

In [37]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [149]:
%config SqlMagic.displaylimit = 500  # Increase limit to 100 rows

In [4]:
%sql postgresql://postgres:Medha%409541@localhost:5432/f1db

Connecting to 'postgresql://postgres:***@localhost:5432/f1db'

In [13]:
%%sql 
SELECT * FROM "Race_Results" LIMIT 5; --testing database setup

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

5 rows affected.

+----------+--------+----------+---------------+--------+------+----------+--------------+---------------+--------+------+-------------+--------------+------------+------+----------------+-----------------+----------+
| resultId | raceId | driverId | constructorId | number | grid | position | positionText | positionOrder | points | laps |     time    | milliseconds | fastestLap | rank | fastestLapTime | fastestLapSpeed | statusId |
+----------+--------+----------+---------------+--------+------+----------+--------------+---------------+--------+------+-------------+--------------+------------+------+----------------+-----------------+----------+
|    1     |   18   |    1     |       1       |   22   |  1   |    1     |      1       |       1       |  10.0  |  58  | 1:34:50.616 |   5690616    |     39     |  2   |    1:27.452    |     218.300     |    1     |
|    2     |   18   |    2     |       2       |   3    |  5   |    2     |      2       |       2       |  8.0   |  58  |    +5.478   |   5696094    |     41     |  3   |    1:27.739    |     217.586     |    1     |
|    3     |   18   |    3     |       3       |   7    |  7   |    3     |      3       |       3       |  6.0   |  58  |    +8.163   |   5698779    |     41     |  5   |    1:28.090    |     216.719     |    1     |
|    4     |   18   |    4     |       4       |   5    |  11  |    4     |      4       |       4       |  5.0   |  58  |   +17.181   |   5707797    |     58     |  7   |    1:28.603    |     215.464     |    1     |
|    5     |   18   |    5     |       1       |   23   |  3   |    5     |      5       |       5       |  4.0   |  58  |   +18.014   |   5708630    |     43     |  1   |    1:27.418    |     218.385     |    1     |
+----------+--------+----------+---------------+--------+------+----------+--------------+---------------+--------+------+-------------+--------------+------------+------+----------------+-----------------+----------+

In [23]:
%%sql 
SELECT r."driverId", d."forename", d."surname", COUNT(DISTINCT "raceId") AS race_count --Finding out the number of races Max and Lewis 
                                                                                       --have participated in so far
FROM "Race_Results" r
JOIN "Driver_Details" d ON r."driverId" = d."driverId"
WHERE r."driverId" IN (1, 830)
GROUP BY r."driverId", d."forename", d."surname";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

2 rows affected.

+----------+----------+------------+------------+
| driverId | forename |  surname   | race_count |
+----------+----------+------------+------------+
|    1     |  Lewis   |  Hamilton  |    344     |
|   830    |   Max    | Verstappen |    197     |
+----------+----------+------------+------------+

In [49]:
%%sql 
SELECT d."driverId", d."forename", d."surname", t."circuitId", t."circuitRef", MIN(l."time") AS best_lap_time --best lap time by tracks for lewis
FROM "Driver_Details" d
JOIN "Lap_Timings" l ON l."driverId" = d."driverId"
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
JOIN "Track_Information" t ON t."circuitId" = rs."circuitId"
WHERE d."driverId" = 1
GROUP BY d."driverId", d."forename", d."surname", t."circuitId", t."circuitRef"
ORDER BY t."circuitRef";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

38 rows affected.

+----------+----------+----------+-----------+----------------+---------------+
| driverId | forename | surname  | circuitId |   circuitRef   | best_lap_time |
+----------+----------+----------+-----------+----------------+---------------+
|    1     |  Lewis   | Hamilton |     1     |  albert_park   |    1:20.613   |
|    1     |  Lewis   | Hamilton |     69    |    americas    |    1:37.392   |
|    1     |  Lewis   | Hamilton |     3     |    bahrain     |    1:32.798   |
|    1     |  Lewis   | Hamilton |     73    |      baku      |    1:43.469   |
|    1     |  Lewis   | Hamilton |     68    |     buddh      |    1:28.721   |
|    1     |  Lewis   | Hamilton |     4     |   catalunya    |    1:16.676   |
|    1     |  Lewis   | Hamilton |     16    |      fuji      |    1:19.560   |
|    1     |  Lewis   | Hamilton |     10    | hockenheimring |    1:15.545   |
|    1     |  Lewis   | Hamilton |     11    |  hungaroring   |    1:16.627   |
|    1     |  Lewis   | Hamilton |     21    |     imola      |    1:15.484   |
|    1     |  Lewis   | Hamilton |     19    |  indianapolis  |    1:13.222   |
|    1     |  Lewis   | Hamilton |     18    |   interlagos   |    1:11.082   |
|    1     |  Lewis   | Hamilton |     5     |    istanbul    |    1:26.529   |
|    1     |  Lewis   | Hamilton |     77    |     jeddah     |    1:30.734   |
|    1     |  Lewis   | Hamilton |     78    |     losail     |    1:25.084   |
|    1     |  Lewis   | Hamilton |     8     |  magny_cours   |    1:16.587   |
|    1     |  Lewis   | Hamilton |     15    |   marina_bay   |    1:35.867   |
|    1     |  Lewis   | Hamilton |     79    |     miami      |    1:30.669   |
|    1     |  Lewis   | Hamilton |     6     |     monaco     |    1:12.909   |
|    1     |  Lewis   | Hamilton |     14    |     monza      |    1:21.779   |
|    1     |  Lewis   | Hamilton |     76    |    mugello     |    1:18.833   |
|    1     |  Lewis   | Hamilton |     20    |  nurburgring   |    1:28.145   |
|    1     |  Lewis   | Hamilton |     75    |    portimao    |    1:18.750   |
|    1     |  Lewis   | Hamilton |     70    | red_bull_ring  |    1:06.719   |
|    1     |  Lewis   | Hamilton |     34    |     ricard     |    1:32.764   |
|    1     |  Lewis   | Hamilton |     32    |   rodriguez    |    1:19.461   |
|    1     |  Lewis   | Hamilton |     2     |     sepang     |    1:34.452   |
|    1     |  Lewis   | Hamilton |     17    |    shanghai    |    1:35.378   |
|    1     |  Lewis   | Hamilton |     9     |  silverstone   |  1:01:38.495  |
|    1     |  Lewis   | Hamilton |     71    |     sochi      |    1:35.761   |
|    1     |  Lewis   | Hamilton |     13    |      spa       |    1:46.580   |
|    1     |  Lewis   | Hamilton |     22    |     suzuka     |    1:30.983   |
|    1     |  Lewis   | Hamilton |     12    |    valencia    |    1:38.884   |
|    1     |  Lewis   | Hamilton |     80    |     vegas      |    1:35.716   |
|    1     |  Lewis   | Hamilton |     7     |   villeneuve   |    1:14.183   |
|    1     |  Lewis   | Hamilton |     24    |   yas_marina   |    1:26.615   |
|    1     |  Lewis   | Hamilton |     35    |    yeongam     |    1:40.459   |
|    1     |  Lewis   | Hamilton |     39    |   zandvoort    |    1:11.097   |
+----------+----------+----------+-----------+----------------+---------------+

In [169]:
%%sql 
SELECT d."driverId", d."forename", d."surname", t."circuitId", t."circuitRef", MIN(l."time") AS best_lap_time --best lap time by tracks for max
FROM "Driver_Details" d
JOIN "Lap_Timings" l ON l."driverId" = d."driverId"
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
JOIN "Track_Information" t ON t."circuitId" = rs."circuitId"
WHERE d."driverId" = 830
GROUP BY d."driverId", d."forename", d."surname", t."circuitId", t."circuitRef"
ORDER BY t."circuitRef";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

31 rows affected.

+----------+----------+------------+-----------+----------------+---------------+
| driverId | forename |  surname   | circuitId |   circuitRef   | best_lap_time |
+----------+----------+------------+-----------+----------------+---------------+
|   830    |   Max    | Verstappen |     1     |  albert_park   |    1:20.342   |
|   830    |   Max    | Verstappen |     69    |    americas    |    1:38.060   |
|   830    |   Max    | Verstappen |     3     |    bahrain     |    1:32.014   |
|   830    |   Max    | Verstappen |     73    |      baku      |    1:44.232   |
|   830    |   Max    | Verstappen |     4     |   catalunya    |    1:16.330   |
|   830    |   Max    | Verstappen |     10    | hockenheimring |    1:15.852   |
|   830    |   Max    | Verstappen |     11    |  hungaroring   |    1:17.103   |
|   830    |   Max    | Verstappen |     21    |     imola      |    1:17.524   |
|   830    |   Max    | Verstappen |     18    |   interlagos   |    1:10.862   |
|   830    |   Max    | Verstappen |     5     |    istanbul    |    1:32.759   |
|   830    |   Max    | Verstappen |     77    |     jeddah     |    1:31.488   |
|   830    |   Max    | Verstappen |     78    |     losail     |    1:23.196   |
|   830    |   Max    | Verstappen |     15    |   marina_bay   |    1:36.575   |
|   830    |   Max    | Verstappen |     79    |     miami      |    1:29.708   |
|   830    |   Max    | Verstappen |     6     |     monaco     |    1:14.260   |
|   830    |   Max    | Verstappen |     14    |     monza      |    1:23.143   |
|   830    |   Max    | Verstappen |     20    |  nurburgring   |    1:28.139   |
|   830    |   Max    | Verstappen |     75    |    portimao    |    1:19.849   |
|   830    |   Max    | Verstappen |     70    | red_bull_ring  |    1:06.145   |
|   830    |   Max    | Verstappen |     34    |     ricard     |    1:34.162   |
|   830    |   Max    | Verstappen |     32    |   rodriguez    |    1:18.892   |
|   830    |   Max    | Verstappen |     2     |     sepang     |    1:34.467   |
|   830    |   Max    | Verstappen |     17    |    shanghai    |    1:36.143   |
|   830    |   Max    | Verstappen |     9     |  silverstone   |    1:27.097   |
|   830    |   Max    | Verstappen |     71    |     sochi      |    1:36.283   |
|   830    |   Max    | Verstappen |     13    |      spa       |    1:46.946   |
|   830    |   Max    | Verstappen |     22    |     suzuka     |    1:33.367   |
|   830    |   Max    | Verstappen |     80    |     vegas      |    1:35.614   |
|   830    |   Max    | Verstappen |     7     |   villeneuve   |    1:13.864   |
|   830    |   Max    | Verstappen |     24    |   yas_marina   |    1:26.103   |
|   830    |   Max    | Verstappen |     39    |   zandvoort    |    1:13.275   |
+----------+----------+------------+-----------+----------------+---------------+

In [94]:
%%sql 
SELECT d."driverId", d."forename", d."surname", COUNT(*) AS total_wins, SUM (r."points") AS total_points -- total wins and points for hamilton
FROM "Driver_Details" d
JOIN "Race_Results" r ON d."driverId" = r."driverId"
WHERE r."positionOrder" = 1 AND d."driverId" = 1 
GROUP BY d."driverId", d."forename", d."surname";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

1 rows affected.

+----------+----------+----------+------------+--------------+
| driverId | forename | surname  | total_wins | total_points |
+----------+----------+----------+------------+--------------+
|    1     |  Lewis   | Hamilton |    104     |    2469.0    |
+----------+----------+----------+------------+--------------+

In [96]:
%%sql 
SELECT d."driverId", d."forename", d."surname", COUNT(*) AS total_wins, SUM (r."points") AS total_points --max's total wins and total points
FROM "Driver_Details" d
JOIN "Race_Results" r ON d."driverId" = r."driverId"
WHERE r."positionOrder" = 1 AND d."driverId" = 830
GROUP BY d."driverId", d."forename", d."surname";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

1 rows affected.

+----------+----------+------------+------------+--------------+
| driverId | forename |  surname   | total_wins | total_points |
+----------+----------+------------+------------+--------------+
|   830    |   Max    | Verstappen |     61     |    1531.5    |
+----------+----------+------------+------------+--------------+

In [100]:
%%sql   
SELECT rs."year", d."driverId", d."forename", d."surname", AVG(SPLIT_PART(l."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l."time", ':', 2)::NUMERIC) AS avg_lap_time_seconds 
FROM "Driver_Details" d -- avg lap time for hamilton over the seasons
JOIN "Lap_Timings" l ON l."driverId" = d."driverId"
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
WHERE d."driverId" = 1
GROUP BY rs."year", d."driverId", d."forename", d."surname"  
ORDER BY rs."year";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

18 rows affected.

+------+----------+----------+----------+----------------------+
| year | driverId | forename | surname  | avg_lap_time_seconds |
+------+----------+----------+----------+----------------------+
| 2007 |    1     |  Lewis   | Hamilton | 90.6008601735776278  |
| 2008 |    1     |  Lewis   | Hamilton | 93.2101953051643192  |
| 2009 |    1     |  Lewis   | Hamilton | 95.0137035398230088  |
| 2010 |    1     |  Lewis   | Hamilton | 101.9919760239760240 |
| 2011 |    1     |  Lewis   | Hamilton | 99.4057926949654492  |
| 2012 |    1     |  Lewis   | Hamilton | 99.4883272727272727  |
| 2013 |    1     |  Lewis   | Hamilton | 99.3982924354243542  |
| 2014 |    1     |  Lewis   | Hamilton | 98.5726546146527117  |
| 2015 |    1     |  Lewis   | Hamilton | 96.2202526785714286  |
| 2016 |    1     |  Lewis   | Hamilton | 101.5083305227655987 |
| 2017 |    1     |  Lewis   | Hamilton | 94.6188485355648536  |
| 2018 |    1     |  Lewis   | Hamilton | 92.5708438247011952  |
| 2019 |    1     |  Lewis   | Hamilton | 91.8993446909667195  |
| 2020 |    1     |  Lewis   | Hamilton | 97.7920705263157895  |
| 2021 |    1     |  Lewis   | Hamilton | 96.2072482269503546  |
| 2022 |    1     |  Lewis   | Hamilton | 97.5738242375601926  |
| 2023 |    1     |  Lewis   | Hamilton | 98.7699850157728707  |
| 2024 |    1     |  Lewis   | Hamilton | 95.5046635220125786  |
+------+----------+----------+----------+----------------------+

In [103]:
%%sql    
SELECT rs."year", d."driverId", d."forename", d."surname", AVG(SPLIT_PART(l."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l."time", ':', 2)::NUMERIC) AS avg_lap_time_seconds 
FROM "Driver_Details" d -- avg lap time for max over the seasons 
JOIN "Lap_Timings" l ON l."driverId" = d."driverId"
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
WHERE d."driverId" = 830
GROUP BY rs."year", d."driverId", d."forename", d."surname"  
ORDER BY rs."year";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

10 rows affected.

+------+----------+----------+------------+----------------------+
| year | driverId | forename |  surname   | avg_lap_time_seconds |
+------+----------+----------+------------+----------------------+
| 2015 |   830    |   Max    | Verstappen | 97.7887034146341463  |
| 2016 |   830    |   Max    | Verstappen | 102.1615501700680272 |
| 2017 |   830    |   Max    | Verstappen | 92.3994285714285714  |
| 2018 |   830    |   Max    | Verstappen | 92.3393238686779059  |
| 2019 |   830    |   Max    | Verstappen | 91.2778771186440678  |
| 2020 |   830    |   Max    | Verstappen | 96.5587937106918239  |
| 2021 |   830    |   Max    | Verstappen | 92.5516556564822461  |
| 2022 |   830    |   Max    | Verstappen | 98.0114327301337530  |
| 2023 |   830    |   Max    | Verstappen | 98.0302279245283019  |
| 2024 |   830    |   Max    | Verstappen | 95.2710881410256410  |
+------+----------+----------+------------+----------------------+

In [167]:
%%sql
SELECT 
    pole_driver."forename" || ' ' || pole_driver."surname" AS pole_position_driver, --who had pole position vs who won the race
    race_winner."forename" || ' ' || race_winner."surname" AS race_winner_driver,
    rs."year"
FROM "Race_Schedule" rs
JOIN "Qualifying_Results" qr 
    ON rs."raceId" = qr."raceId"
JOIN "Race_Results" rr 
    ON rs."raceId" = rr."raceId"
JOIN "Driver_Details" pole_driver 
    ON qr."driverId" = pole_driver."driverId"
JOIN "Driver_Details" race_winner 
    ON rr."driverId" = race_winner."driverId"
WHERE 
    qr."position" = 1  
    AND rr."positionOrder" = 1  
    AND rs."year" BETWEEN 2020 AND 2024  
ORDER BY rs."year";

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

95 rows affected.

+----------------------+--------------------+------+
| pole_position_driver | race_winner_driver | year |
+----------------------+--------------------+------+
|   Valtteri Bottas    |  Valtteri Bottas   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|   Valtteri Bottas    |   Max Verstappen   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |    Pierre Gasly    | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |  Valtteri Bottas   | 2020 |
|   Valtteri Bottas    |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|   Valtteri Bottas    |   Lewis Hamilton   | 2020 |
|     Lance Stroll     |   Lewis Hamilton   | 2020 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2020 |
|   Valtteri Bottas    |    Sergio Pérez    | 2020 |
|    Max Verstappen    |   Max Verstappen   | 2020 |
|    Max Verstappen    |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |   Max Verstappen   | 2021 |
|   Valtteri Bottas    |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2021 |
|   Charles Leclerc    |   Max Verstappen   | 2021 |
|   Charles Leclerc    |    Sergio Pérez    | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |    Esteban Ocon    | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|   Valtteri Bottas    |  Daniel Ricciardo  | 2021 |
|     Lando Norris     |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |  Valtteri Bottas   | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|   Valtteri Bottas    |   Max Verstappen   | 2021 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2021 |
|    Lewis Hamilton    |   Lewis Hamilton   | 2021 |
|    Max Verstappen    |   Max Verstappen   | 2021 |
|   Charles Leclerc    |  Charles Leclerc   | 2022 |
|     Sergio Pérez     |   Max Verstappen   | 2022 |
|   Charles Leclerc    |  Charles Leclerc   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|   Charles Leclerc    |   Max Verstappen   | 2022 |
|   Charles Leclerc    |   Max Verstappen   | 2022 |
|   Charles Leclerc    |    Sergio Pérez    | 2022 |
|   Charles Leclerc    |   Max Verstappen   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|     Carlos Sainz     |    Carlos Sainz    | 2022 |
|    Max Verstappen    |  Charles Leclerc   | 2022 |
|   Charles Leclerc    |   Max Verstappen   | 2022 |
|    George Russell    |   Max Verstappen   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|   Charles Leclerc    |   Max Verstappen   | 2022 |
|   Charles Leclerc    |    Sergio Pérez    | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|     Carlos Sainz     |   Max Verstappen   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|   Kevin Magnussen    |   George Russell   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2022 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|     Sergio Pérez     |    Sergio Pérez    | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|   Charles Leclerc    |    Sergio Pérez    | 2023 |
|     Sergio Pérez     |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Lewis Hamilton    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|     Carlos Sainz     |   Max Verstappen   | 2023 |
|     Carlos Sainz     |    Carlos Sainz    | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|   Charles Leclerc    |   Max Verstappen   | 2023 |
|   Charles Leclerc    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|   Charles Leclerc    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2023 |
|    Max Verstappen    |   Max Verstappen   | 2024 |
|    Max Verstappen    |   Max Verstappen   | 2024 |
|    Max Verstappen    |    Carlos Sainz    | 2024 |
|    Max Verstappen    |   Max Verstappen   | 2024 |
|    Max Verstappen    |   Max Verstappen   | 2024 |
|    Max Verstappen    |    Lando Norris    | 2024 |
|    Max Verstappen    |   Max Verstappen   | 2024 |
|   Charles Leclerc    |  Charles Leclerc   | 2024 |
|    George Russell    |   Max Verstappen   | 2024 |
|     Lando Norris     |   Max Verstappen   | 2024 |
|    Max Verstappen    |   George Russell   | 2024 |
|    George Russell    |   Lewis Hamilton   | 2024 |
+----------------------+--------------------+------+

In [239]:
%%sql 
SELECT  td."constructorRef" ,SUM(cr."points") as total_points, rs."year" --total points for teams between 2000 and 2024
FROM "Team_Details" td 
JOIN "Constructor_Rankings" cr ON cr."constructorId" = td."constructorId"
JOIN "Race_Schedule" rs ON cr."raceId" = rs."raceId"
WHERE cr."constructorId" = td."constructorId" AND rs."year" BETWEEN 2000 AND 2024  
GROUP BY rs."year",td."constructorRef"
ORDER BY  rs."year" DESC, total_points DESC;

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

266 rows affected.

+----------------+--------------+------+
| constructorRef | total_points | year |
+----------------+--------------+------+
|    red_bull    |    2706.0    | 2024 |
|    ferrari     |    2206.0    | 2024 |
|    mclaren     |    1734.0    | 2024 |
|    mercedes    |    1085.0    | 2024 |
|  aston_martin  |    486.0     | 2024 |
|       rb       |    200.0     | 2024 |
|      haas      |     95.0     | 2024 |
|     alpine     |     35.0     | 2024 |
|    williams    |     12.0     | 2024 |
|     sauber     |     0.0      | 2024 |
|    red_bull    |   10158.0    | 2023 |
|    mercedes    |    4917.0    | 2023 |
|    ferrari     |    4289.0    | 2023 |
|  aston_martin  |    3845.0    | 2023 |
|    mclaren     |    2491.0    | 2023 |
|     alpine     |    1307.0    | 2023 |
|    williams    |    293.0     | 2023 |
|      alfa      |    220.0     | 2023 |
|      haas      |    209.0     | 2023 |
|   alphatauri   |    134.0     | 2023 |
|    red_bull    |    8439.0    | 2022 |
|    ferrari     |    6584.0    | 2022 |
|    mercedes    |    5596.0    | 2022 |
|     alpine     |    1887.0    | 2022 |
|    mclaren     |    1852.0    | 2022 |
|      alfa      |    936.0     | 2022 |
|      haas      |    562.0     | 2022 |
|   alphatauri   |    549.0     | 2022 |
|  aston_martin  |    489.0     | 2022 |
|    williams    |     89.0     | 2022 |
|    mercedes    |    6915.5    | 2021 |
|    red_bull    |    6786.5    | 2021 |
|    ferrari     |    3687.5    | 2021 |
|    mclaren     |    3641.0    | 2021 |
|     alpine     |    1517.0    | 2021 |
|   alphatauri   |    1444.0    | 2021 |
|  aston_martin  |    1010.0    | 2021 |
|    williams    |    256.0     | 2021 |
|      alfa      |    103.0     | 2021 |
|      haas      |     0.0      | 2021 |
|    mercedes    |    5476.0    | 2020 |
|    red_bull    |    2867.0    | 2020 |
|    mclaren     |    1730.0    | 2020 |
|  racing_point  |    1637.0    | 2020 |
|    renault     |    1442.0    | 2020 |
|    ferrari     |    1285.0    | 2020 |
|   alphatauri   |    871.0     | 2020 |
|      alfa      |     74.0     | 2020 |
|      haas      |     29.0     | 2020 |
|    williams    |     0.0      | 2020 |
|    mercedes    |    8631.0    | 2019 |
|    ferrari     |    5735.0    | 2019 |
|    red_bull    |    4399.0    | 2019 |
|    mclaren     |    1403.0    | 2019 |
|    renault     |    920.0     | 2019 |
|   toro_rosso   |    759.0     | 2019 |
|  racing_point  |    712.0     | 2019 |
|      alfa      |    558.0     | 2019 |
|      haas      |    425.0     | 2019 |
|    williams    |     11.0     | 2019 |
|    mercedes    |    6903.0    | 2018 |
|    ferrari     |    6377.0    | 2018 |
|    red_bull    |    4338.0    | 2018 |
|    renault     |    1479.0    | 2018 |
|      haas      |    1084.0    | 2018 |
|    mclaren     |    972.0     | 2018 |
|  force_india   |    681.0     | 2018 |
|   toro_rosso   |    474.0     | 2018 |
|     sauber     |    396.0     | 2018 |
|    williams    |     96.0     | 2018 |
|    mercedes    |    6928.0    | 2017 |
|    ferrari     |    5749.0    | 2017 |
|    red_bull    |    3674.0    | 2017 |
|  force_india   |    1924.0    | 2017 |
|    williams    |    868.0     | 2017 |
|   toro_rosso   |    708.0     | 2017 |
|    renault     |    538.0     | 2017 |
|      haas      |    537.0     | 2017 |
|    mclaren     |    207.0     | 2017 |
|     sauber     |     77.0     | 2017 |
|    mercedes    |    8085.0    | 2016 |
|    red_bull    |    4842.0    | 2016 |
|    ferrari     |    4566.0    | 2016 |
|    williams    |    1898.0    | 2016 |
|  force_india   |    1665.0    | 2016 |
|    mclaren     |    813.0     | 2016 |
|   toro_rosso   |    802.0     | 2016 |
|      haas      |    522.0     | 2016 |
|    renault     |    121.0     | 2016 |
|     manor      |     13.0     | 2016 |
|     sauber     |     4.0      | 2016 |
|    mercedes    |    7139.0    | 2015 |
|    ferrari     |    4457.0    | 2015 |
|    williams    |    2796.0    | 2015 |
|    red_bull    |    1740.0    | 2015 |
|  force_india   |    1010.0    | 2015 |
|    lotus_f1    |    737.0     | 2015 |
|   toro_rosso   |    613.0     | 2015 |
|     sauber     |    469.0     | 2015 |
|    mclaren     |    229.0     | 2015 |
|     manor      |     0.0      | 2015 |
|    mercedes    |    6830.0    | 2014 |
|    red_bull    |    3793.0    | 2014 |
|    williams    |    2439.0    | 2014 |
|    ferrari     |    2314.0    | 2014 |
|    mclaren     |    1757.0    | 2014 |
|  force_india   |    1680.0    | 2014 |
|   toro_rosso   |    328.0     | 2014 |
|    lotus_f1    |    122.0     | 2014 |
|    marussia    |     28.0     | 2014 |
|     sauber     |     0.0      | 2014 |
|    caterham    |     0.0      | 2014 |
|    red_bull    |    5538.0    | 2013 |
|    ferrari     |    3787.0    | 2013 |
|    mercedes    |    3712.0    | 2013 |
|    lotus_f1    |    3319.0    | 2013 |
|    mclaren     |    1072.0    | 2013 |
|  force_india   |    971.0     | 2013 |
|   toro_rosso   |    405.0     | 2013 |
|     sauber     |    368.0     | 2013 |
|    williams    |     18.0     | 2013 |
|    marussia    |     0.0      | 2013 |
|    caterham    |     0.0      | 2013 |
|    red_bull    |    4785.0    | 2012 |
|    mclaren     |    3890.0    | 2012 |
|    ferrari     |    3659.0    | 2012 |
|    lotus_f1    |    3307.0    | 2012 |
|    mercedes    |    1834.0    | 2012 |
|     sauber     |    1527.0    | 2012 |
|  force_india   |    1053.0    | 2012 |
|    williams    |    928.0     | 2012 |
|   toro_rosso   |    227.0     | 2012 |
|    marussia    |     0.0      | 2012 |
|    caterham    |     0.0      | 2012 |
|      hrt       |     0.0      | 2012 |
|    red_bull    |    6679.0    | 2011 |
|    mclaren     |    4896.0    | 2011 |
|    ferrari     |    3546.0    | 2011 |
|    mercedes    |    1499.0    | 2011 |
|    renault     |    1102.0    | 2011 |
|     sauber     |    523.0     | 2011 |
|  force_india   |    499.0     | 2011 |
|   toro_rosso   |    384.0     | 2011 |
|    williams    |     62.0     | 2011 |
|      hrt       |     0.0      | 2011 |
|     virgin     |     0.0      | 2011 |
|  lotus_racing  |     0.0      | 2011 |
|    red_bull    |    4734.0    | 2010 |
|    mclaren     |    4705.0    | 2010 |
|    ferrari     |    3966.0    | 2010 |
|    mercedes    |    2260.0    | 2010 |
|    renault     |    1708.0    | 2010 |
|  force_india   |    791.0     | 2010 |
|    williams    |    576.0     | 2010 |
|     sauber     |    311.0     | 2010 |
|   toro_rosso   |    139.0     | 2010 |
|     virgin     |     0.0      | 2010 |
|  lotus_racing  |     0.0      | 2010 |
|      hrt       |     0.0      | 2010 |
|     brawn      |    1752.0    | 2009 |
|    red_bull    |    1280.0    | 2009 |
|     toyota     |    596.0     | 2009 |
|    ferrari     |    577.0     | 2009 |
|    mclaren     |    514.0     | 2009 |
|    williams    |    323.0     | 2009 |
|    renault     |    241.0     | 2009 |
|   bmw_sauber   |    216.0     | 2009 |
|   toro_rosso   |     83.0     | 2009 |
|  force_india   |     73.0     | 2009 |
|    ferrari     |    1686.0    | 2008 |
|    mclaren     |    1491.0    | 2008 |
|   bmw_sauber   |    1431.0    | 2008 |
|    renault     |    508.0     | 2008 |
|     toyota     |    492.0     | 2008 |
|    red_bull    |    346.0     | 2008 |
|    williams    |    301.0     | 2008 |
|   toro_rosso   |    246.0     | 2008 |
|     honda      |    168.0     | 2008 |
|  force_india   |     0.0      | 2008 |
|  super_aguri   |     0.0      | 2008 |
|    mclaren     |    2072.0    | 2007 |
|    ferrari     |    1734.0    | 2007 |
|   bmw_sauber   |    939.0     | 2007 |
|    renault     |    484.0     | 2007 |
|    williams    |    272.0     | 2007 |
|    red_bull    |    183.0     | 2007 |
|     toyota     |    146.0     | 2007 |
|  super_aguri   |     50.0     | 2007 |
|     honda      |     23.0     | 2007 |
|   toro_rosso   |     16.0     | 2007 |
|     spyker     |     3.0      | 2007 |
|    renault     |    2065.0    | 2006 |
|    ferrari     |    1796.0    | 2006 |
|    mclaren     |    1135.0    | 2006 |
|     honda      |    687.0     | 2006 |
|   bmw_sauber   |    346.0     | 2006 |
|     toyota     |    300.0     | 2006 |
|    williams    |    166.0     | 2006 |
|    red_bull    |    165.0     | 2006 |
|   toro_rosso   |     9.0      | 2006 |
|      mf1       |     0.0      | 2006 |
|   spyker_mf1   |     0.0      | 2006 |
|  super_aguri   |     0.0      | 2006 |
|    renault     |    1853.0    | 2005 |
|    mclaren     |    1605.0    | 2005 |
|    ferrari     |    1091.0    | 2005 |
|     toyota     |    999.0     | 2005 |
|    williams    |    785.0     | 2005 |
|    red_bull    |    398.0     | 2005 |
|      bar       |    237.0     | 2005 |
|     sauber     |    207.0     | 2005 |
|     jordan     |    125.0     | 2005 |
|    minardi     |     77.0     | 2005 |
|    ferrari     |    2636.0    | 2004 |
|    renault     |    1174.0    | 2004 |
|      bar       |    1091.0    | 2004 |
|    williams    |    764.0     | 2004 |
|    mclaren     |    475.0     | 2004 |
|     sauber     |    279.0     | 2004 |
|     toyota     |     97.0     | 2004 |
|     jaguar     |     84.0     | 2004 |
|     jordan     |     59.0     | 2004 |
|    minardi     |     10.0     | 2004 |
|    ferrari     |    1336.0    | 2003 |
|    mclaren     |    1259.0    | 2003 |
|    williams    |    1209.0    | 2003 |
|    renault     |    783.0     | 2003 |
|      bar       |    184.0     | 2003 |
|     jordan     |    156.0     | 2003 |
|     sauber     |    147.0     | 2003 |
|     jaguar     |    129.0     | 2003 |
|     toyota     |    101.0     | 2003 |
|    minardi     |     0.0      | 2003 |
|    ferrari     |    1796.0    | 2002 |
|    williams    |    989.0     | 2002 |
|    mclaren     |    573.0     | 2002 |
|    renault     |    209.0     | 2002 |
|     sauber     |    136.0     | 2002 |
|     jordan     |     73.0     | 2002 |
|     jaguar     |     67.0     | 2002 |
|      bar       |     45.0     | 2002 |
|    minardi     |     34.0     | 2002 |
|     toyota     |     32.0     | 2002 |
|     arrows     |     24.0     | 2002 |
|    ferrari     |    1631.0    | 2001 |
|    mclaren     |    906.0     | 2001 |
|    williams    |    624.0     | 2001 |
|     sauber     |    243.0     | 2001 |
|     jordan     |    219.0     | 2001 |
|      bar       |    181.0     | 2001 |
|     jaguar     |     64.0     | 2001 |
|    benetton    |     61.0     | 2001 |
|     prost      |     37.0     | 2001 |
|     arrows     |     12.0     | 2001 |
|    minardi     |     0.0      | 2001 |
|    ferrari     |    1493.0    | 2000 |
|    mclaren     |    1403.0    | 2000 |
|    williams    |    342.0     | 2000 |
|    benetton    |    246.0     | 2000 |
|     jordan     |    181.0     | 2000 |
|      bar       |    169.0     | 2000 |
|     sauber     |     59.0     | 2000 |
|     arrows     |     51.0     | 2000 |
|     jaguar     |     34.0     | 2000 |
|    minardi     |     0.0      | 2000 |
|     prost      |     0.0      | 2000 |
+----------------+--------------+------+

In [193]:
%%sql 
SELECT 
    td."constructorRef" AS team_name, -- races participated in vs races qualitfied in team wise
    COUNT(DISTINCT qr."raceId") AS total_races_participated,
    COUNT(DISTINCT CASE WHEN qr."q3" IS NOT NULL THEN qr."raceId" END) AS times_qualified_for_q3
FROM "Team_Details" td
JOIN "Qualifying_Results" qr ON td."constructorId" = qr."constructorId"
GROUP BY td."constructorRef"
ORDER BY times_qualified_for_q3 DESC;

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

47 rows affected.

+--------------+--------------------------+------------------------+
|  team_name   | total_races_participated | times_qualified_for_q3 |
+--------------+--------------------------+------------------------+
|   ferrari    |           482            |          482           |
|   mclaren    |           482            |          482           |
|   williams   |           482            |          481           |
|   red_bull   |           381            |          381           |
|    sauber    |           308            |          307           |
|   mercedes   |           293            |          293           |
|  toro_rosso  |           268            |          268           |
|   renault    |           263            |          263           |
| force_india  |           212            |          212           |
|     haas     |           178            |          177           |
|    toyota    |           125            |          125           |
|   minardi    |           119            |          119           |
|    jordan    |           119            |          119           |
|     alfa     |           104            |          103           |
|  alphatauri  |            83            |           83           |
|   lotus_f1   |            77            |           77           |
| aston_martin |            78            |           77           |
|    alpine    |            78            |           76           |
|  bmw_sauber  |            70            |           70           |
|   benetton   |            64            |           64           |
|     bar      |            61            |           61           |
|   marussia   |            60            |           60           |
|     hrt      |            58            |           58           |
|   tyrrell    |            56            |           56           |
|   caterham   |            56            |           56           |
|    honda     |            53            |           53           |
|    jaguar    |            41            |           41           |
|   footwork   |            39            |           39           |
|    ligier    |            39            |           39           |
| super_aguri  |            39            |           39           |
| racing_point |            38            |           38           |
| lotus_racing |            38            |           38           |
|    virgin    |            38            |           38           |
|    manor     |            34            |           34           |
|    arrows    |            26            |           26           |
|    prost     |            25            |           25           |
|    forti     |            21            |           21           |
|   pacific    |            21            |           21           |
|    simtek    |            20            |           20           |
|   stewart    |            20            |           20           |
|    brawn     |            17            |           17           |
|    spyker    |            17            |           17           |
|  larrousse   |            15            |           15           |
|  team_lotus  |            15            |           15           |
|     mf1      |            14            |           14           |
|      rb      |            12            |           12           |
|  spyker_mf1  |            4             |           4            |
+--------------+--------------------------+------------------------+

In [205]:
%%sql
SELECT t."circuitRef", AVG(SPLIT_PART(l."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l."time", ':', 2)::NUMERIC) AS avg_lap_time_seconds, MIN(l."time") AS fastest_lap, MAX(l."time") AS slowest_lap
FROM "Lap_Timings" l --avg,slowest and fastest lap circuit wise
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
JOIN "Track_Information" t ON t."circuitId" = rs."circuitId"
GROUP BY t."circuitId", t."circuitRef"
ORDER BY avg_lap_time_seconds ASC;

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

41 rows affected.

+----------------+----------------------+-------------+-------------+
|   circuitRef   | avg_lap_time_seconds | fastest_lap | slowest_lap |
+----------------+----------------------+-------------+-------------+
| red_bull_ring  | 74.2184689680350479  |   1:05.619  |   9:24.047  |
|  indianapolis  | 78.8806972016264052  |   1:10.399  |   3:07.383  |
|  magny_cours   | 81.9489361967786240  |   1:15.045  |   8:30.293  |
|   villeneuve   | 84.3562255090280446  |   1:13.078  |   9:06.038  |
|   interlagos   | 84.8860078605502385  |   1:10.540  |   7:57.507  |
|    portimao    | 85.3832010268562401  |   1:18.750  |   2:22.886  |
|     jerez      | 87.0721464684014870  |   1:23.135  |   1:52.897  |
|   rodriguez    | 87.4854384410139127  |   1:17.774  |   3:24.844  |
|  hungaroring   | 87.6332119435037582  |   1:16.207  |   9:45.712  |
|     monaco     | 88.4438191077161519  |   1:12.909  |   6:41.558  |
|   catalunya    | 88.4727464005235602  |   1:15.641  |   6:31.146  |
|    estoril     | 88.5319299065420561  |   1:22.873  |   4:26.095  |
| hockenheimring | 89.1670877470355731  |   1:13.780  |   7:03.979  |
|     imola      | 90.7674238847642617  |   1:15.484  |   4:39.926  |
|     monza      | 91.1556388371651150  |   1:21.046  |   8:30.556  |
|   zandvoort    | 91.6047984363547520  |   1:11.097  |  43:45.541  |
|     losail     | 92.0621620217288616  |   1:23.196  |   2:33.406  |
|     buddh      | 92.9923912117177097  |   1:27.249  |   3:11.592  |
|    istanbul    | 94.7919039124864492  |   1:24.770  |   5:13.638  |
|  nurburgring   | 95.4742368814729574  |   1:18.354  |   5:31.478  |
|     galvez     | 95.4904337279815189  |   1:27.981  |   4:57.378  |
|     miami      | 96.3891616712079927  |   1:29.708  |   2:57.593  |
|      fuji      | 98.0117936440677966  |   1:18.426  |   5:08.436  |
|  albert_park   | 98.9858561081603090  |   1:19.813  |   9:18.552  |
|  silverstone   | 99.4427591850828729  | 1:01:07.384 |   6:22.273  |
|    bahrain     | 99.7751434305120628  |   0:55.404  |   6:45.395  |
|     ricard     | 101.2221312262958281 |   1:32.740  |   3:39.223  |
|   yas_marina   | 105.3390119820269596 |   1:26.103  |   3:01.543  |
|     suzuka     | 106.0346968678185377 |   1:30.983  |   9:13.758  |
|     sochi      | 106.1373555614830621 |   1:35.761  |   3:19.317  |
|    valencia    | 106.2257590097675985 |   1:38.683  |   6:04.173  |
|    americas    | 106.5636982657920748 |   1:36.169  |   3:05.741  |
|    shanghai    | 107.2326242831394396 |   1:32.238  |   4:15.723  |
|     vegas      | 107.7517688229056204 |   1:35.490  |   3:07.579  |
|     sepang     | 110.0465112218086271 |   1:34.080  |   8:24.090  |
|     jeddah     | 112.9739965704486996 |   1:30.734  |   3:38.147  |
|   marina_bay   | 118.4018746903778977 |   1:35.867  |   6:11.753  |
|      spa       | 120.9047730604925901 |   1:45.108  |   8:44.604  |
|      baku      | 123.3650365417508941 |   1:43.009  |   4:04.093  |
|    yeongam     | 131.1538064657055483 |   1:39.605  |  49:02.501  |
|    mugello     | 141.4052455012853470 |   1:18.833  |   8:10.852  |
+----------------+----------------------+-------------+-------------+

In [221]:
%%sql
SELECT 
    t."circuitRef", --avg lap time difference between p2 and p1 circuit wise 
    AVG(
        (SPLIT_PART(l2."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l2."time", ':', 2)::NUMERIC) 
        - (SPLIT_PART(l1."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l1."time", ':', 2)::NUMERIC)
    ) AS avg_P1_P2_diff
FROM "Lap_Timings" l1
JOIN "Race_Schedule" rs ON rs."raceId" = l1."raceId"
JOIN "Driver_Rankings" dr1 ON dr1."raceId" = rs."raceId" AND dr1."position" = 1
JOIN "Lap_Timings" l2 ON l2."raceId" = rs."raceId"
JOIN "Driver_Rankings" dr2 ON dr2."raceId" = rs."raceId" AND dr2."position" = 2
JOIN "Track_Information" t ON t."circuitId" = rs."circuitId"
WHERE l1."driverId" = dr1."driverId" 
  AND l2."driverId" = dr2."driverId"
GROUP BY t."circuitRef"
ORDER BY avg_P1_P2_diff DESC;

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

41 rows affected.

+----------------+-------------------------+
|   circuitRef   |      avg_p1_p2_diff     |
+----------------+-------------------------+
|    yeongam     |   13.2352478887232986   |
|      baku      |    5.7989012904307022   |
|     suzuka     |    3.0925477914231065   |
|      fuji      |    1.2010145107794362   |
|   villeneuve   |  0.58001574318115261494 |
|     buddh      |  0.53426111111111111111 |
|    istanbul    |  0.48456757944557133198 |
|     losail     |  0.43366666666666666667 |
|    portimao    |  0.41469696969696969697 |
|  magny_cours   |  0.29346618219006151510 |
|     sochi      |  0.28794769079447400188 |
|   yas_marina   |  0.28074817257361588304 |
|  indianapolis  |  0.22104943933252463091 |
|    bahrain     |  0.21632240428622752620 |
|      spa       |  0.20150932647468871689 |
|  albert_park   |  0.20077279523393292543 |
|     ricard     |  0.19934144511149228130 |
|    americas    |  0.19560064935064935065 |
|     monaco     |  0.17565417180161875895 |
|   zandvoort    |  0.17096759259259259259 |
|     sepang     |  0.16497338242626471829 |
|    valencia    |  0.14310526315789473684 |
|     imola      |  0.12953425255431008828 |
|  silverstone   |  0.11962207503767748076 |
|    mugello     |  0.08271186440677966102 |
| red_bull_ring  |  0.08254120788868518381 |
|   catalunya    |  0.05194904158279382696 |
|     miami      |  0.05050292397660818713 |
|     vegas      |  0.04482000000000000000 |
|     jerez      |  0.03965217391304347826 |
|  hungaroring   |  0.02524648186100025168 |
|     jeddah     |  0.02005500000000000000 |
|     monza      | -0.02069246049661399549 |
|     galvez     | -0.07452777777777777778 |
|    shanghai    | -0.09425030888030888031 |
|  nurburgring   | -0.09505090691945958050 |
| hockenheimring | -0.10162101428873090730 |
|   marina_bay   | -0.11567664988685170646 |
|   interlagos   | -0.17629231186358980539 |
|   rodriguez    | -0.19103689744098393176 |
|    estoril     | -0.28522857142857142857 |
+----------------+-------------------------+

In [229]:
%%sql
SELECT DISTINCT ON (t."circuitRef") t."circuitRef", l."driverId", d."forename", d."surname", rs."year", 
    SPLIT_PART(l."time", ':', 1)::NUMERIC * 60 + SPLIT_PART(l."time", ':', 2)::NUMERIC AS fastest_lap_time_seconds
FROM "Lap_Timings" l --fastest lap on each track
JOIN "Race_Schedule" rs ON rs."raceId" = l."raceId"
JOIN "Track_Information" t ON t."circuitId" = rs."circuitId"
JOIN "Driver_Details" d ON d."driverId" = l."driverId"
ORDER BY t."circuitRef", fastest_lap_time_seconds ASC;

Running query in 'postgresql://postgres:***@localhost:5432/f1db'

41 rows affected.

+----------------+----------+--------------+---------------+------+--------------------------+
|   circuitRef   | driverId |   forename   |    surname    | year | fastest_lap_time_seconds |
+----------------+----------+--------------+---------------+------+--------------------------+
|  albert_park   |   844    |   Charles    |    Leclerc    | 2024 |          79.813          |
|    americas    |   844    |   Charles    |    Leclerc    | 2019 |          96.169          |
|    bahrain     |   847    |    George    |    Russell    | 2020 |          55.404          |
|      baku      |   844    |   Charles    |    Leclerc    | 2019 |         103.009          |
|     buddh      |    20    |  Sebastian   |     Vettel    | 2011 |          87.249          |
|   catalunya    |    21    |  Giancarlo   |   Fisichella  | 2005 |          75.641          |
|    estoril     |    35    |   Jacques    |   Villeneuve  | 1996 |          82.873          |
|      fuji      |    13    |    Felipe    |     Massa     | 2008 |          78.426          |
|     galvez     |    77    |   Gerhard    |     Berger    | 1997 |          87.981          |
| hockenheimring |    8     |     Kimi     |   Räikkönen   | 2004 |          73.780          |
|  hungaroring   |    30    |   Michael    |   Schumacher  | 2002 |          76.207          |
|     imola      |    1     |    Lewis     |    Hamilton   | 2020 |          75.484          |
|  indianapolis  |    22    |    Rubens    |  Barrichello  | 2004 |          70.399          |
|   interlagos   |   822    |   Valtteri   |     Bottas    | 2018 |          70.540          |
|    istanbul    |    31    |     Juan     | Pablo Montoya | 2005 |          84.770          |
|     jeddah     |    1     |    Lewis     |    Hamilton   | 2021 |          90.734          |
|     jerez      |    49    | Heinz-Harald |    Frentzen   | 1997 |          83.135          |
|     losail     |   830    |     Max      |   Verstappen  | 2021 |          83.196          |
|  magny_cours   |    14    |    David     |   Coulthard   | 2002 |          75.045          |
|   marina_bay   |    1     |    Lewis     |    Hamilton   | 2023 |          95.867          |
|     miami      |   830    |     Max      |   Verstappen  | 2023 |          89.708          |
|     monaco     |    1     |    Lewis     |    Hamilton   | 2021 |          72.909          |
|     monza      |    22    |    Rubens    |  Barrichello  | 2004 |          81.046          |
|    mugello     |    1     |    Lewis     |    Hamilton   | 2020 |          78.833          |
|  nurburgring   |    31    |     Juan     | Pablo Montoya | 2001 |          78.354          |
|    portimao    |    1     |    Lewis     |    Hamilton   | 2020 |          78.750          |
| red_bull_ring  |   832    |    Carlos    |     Sainz     | 2020 |          65.619          |
|     ricard     |    20    |  Sebastian   |     Vettel    | 2019 |          92.740          |
|   rodriguez    |   822    |   Valtteri   |     Bottas    | 2021 |          77.774          |
|     sepang     |    20    |  Sebastian   |     Vettel    | 2017 |          94.080          |
|    shanghai    |    30    |   Michael    |   Schumacher  | 2004 |          92.238          |
|  silverstone   |   155    |    Kamui     |   Kobayashi   | 2014 |            61            |
|     sochi      |    1     |    Lewis     |    Hamilton   | 2019 |          95.761          |
|      spa       |    8     |     Kimi     |   Räikkönen   | 2004 |         105.108          |
|     suzuka     |    1     |    Lewis     |    Hamilton   | 2019 |          90.983          |
|    valencia    |    10    |     Timo     |     Glock     | 2009 |          98.683          |
|     vegas      |   857    |    Oscar     |    Piastri    | 2023 |          95.490          |
|   villeneuve   |   822    |   Valtteri   |     Bottas    | 2019 |          73.078          |
|   yas_marina   |   830    |     Max      |   Verstappen  | 2021 |          86.103          |
|    yeongam     |    20    |  Sebastian   |     Vettel    | 2011 |          99.605          |
|   zandvoort    |    1     |    Lewis     |    Hamilton   | 2021 |          71.097          |
+----------------+----------+--------------+---------------+------+--------------------------+

In [231]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\medha\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\medha\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\medha\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\medha\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\medha\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\medha\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)